### ISSUE TITLE
How to send String JSON Array as parameter?

### ISSUE THREAD

**Issue by dtomicAZ** [devxoul/MoyaSugar#22]
I want to send json array in body of request with MoyaSugar, e.g. [1,2,3]

Can someone provide me solution, thanks.

Here is some examples using Moya:
https://github.com/Moya/Moya/issues/467

but I can't get it work with MoyaSugar.

**Comment by devxoul** [comment]
@dtomicAZ, if you're following https://github.com/Moya/Moya/issues/467#issuecomment-246747330, you may use:

```swift
var parameters: Parameters? {
  // `JsonArrayEncoding` from @tdouglas1313's comment
  return JsonArrayEncoding() => [
    "jsonArray": ["foo", "bar"]
  ]
}
```

**Comment by dtomicAZ** [comment]
Great, it is working, thank you.
